steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/wyownproject/vm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--tag=gcr.io/wyownproject/vm', '.']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f','vm.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=k0'
images: ['gcr.io/wyownproject/vm']